### ISSUE TITLE
Readme for Tests

### ISSUE THREAD

**Issue by sshadmand** [CyberReboot/vcontrol#105]
@cglewis, I'd like to knock out a few of the test issues, but could use a kickstart. Could you add some Readme info on how to run the tests so I may build off of what exists, please?

**Comment by cglewis** [comment]
@sshadmand would be happy to, I'll have something for you tomorrow.  thanks!

**Comment by cglewis** [comment]
check out: https://github.com/CyberReboot/vcontrol/blob/master/docs/TEST.md
let me know if anything doesn't make sense.
